Loading python/3.7.3
  Loading requirement: tcl/8.6.8 gcc/8.3.0
WPQUEG Quantization: 288888
Epoch 1 | Loss: 2.1627 Train Acc: 0.5393 Test Acc: 0.1757 Train Time: 267.3971s Inference Time: 63.1043s
Traceback (most recent call last):
  File "local_error_mnist_sweep.py", line 236, in <module>
    run_main(x_train, x_test, y_train, y_test, args['dir'] + '/wb{0}'.format(i), i)
  File "local_error_mnist_sweep.py", line 210, in run_main
    results = {'layer1':[layer1.weights, layer1.bias], 'layer2':[layer1.weights, layer1.bias], 'layer3':[layer1.weights, layer1.bias], 'layer4':[layer1.weights, layer1.bias], 'test_acc': test_acc, 'train_acc': train_acc, 'loss':[loss_hist, loss_hist2, loss_his3, loss_hist4], 'train_idx':shuffle_idx_ta, 'test_idx':shuffle_idx_te}
NameError: name 'loss_his3' is not defined
